import { ethers } from "ethers";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const RPC_URL     = process.env.RPC_URL     ?? "http://127.0.0.1:8545";
// Hardhat Account #0 — pre-funded on `npx hardhat node`
const PRIVATE_KEY = process.env.PRIVATE_KEY ?? "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";
const NETWORK     = process.env.NETWORK     ?? "local";

async function main() {
  const artifactPath = path.join(
    __dirname, "../artifacts/contracts/ChainCards.sol/ChainCards.json"
  );
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));

  const provider = new ethers.JsonRpcProvider(RPC_URL);
  const wallet   = new ethers.Wallet(PRIVATE_KEY, provider);

  console.log("Deploying from:", wallet.address);

  const factory  = new ethers.ContractFactory(artifact.abi, artifact.bytecode, wallet);
  const contract = await factory.deploy();
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  console.log("ChainCards deployed to:", address);

  const outPath = path.join(__dirname, "../../web/src/config/deployments.ts");
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(
    outPath,
    `// Auto-generated by deploy script — do not edit manually\n` +
    `export const deployment = ${JSON.stringify({ address, abi: artifact.abi, network: NETWORK, deployedAt: new Date().toISOString() }, null, 2)} as const;\n`
  );
  console.log("Updated", outPath);
}

main().catch((e) => { console.error(e); process.exit(1); });
